; ==========================================================
; Proyecto: BIO-ALERT (AXIS.ops)
; Nodo: BIO-ACOUSTIC-BREAD (Módulo de Cría)
; Estado: EN ESPERA / PLACEHOLDER
; ==========================================================
;
; Este archivo es un marcador de posición para el futuro 
; desarrollo del nodo "Bread". 
;
; Actualmente contiene la configuración base para que 
; PlatformIO reconozca la carpeta dentro del Monorepo. 
;
; PROXIMAMENTE:
; - Se actualizará la placa si decidimos usar un hardware distinto.
; - Se añadirán en 'lib_deps' las dependencias para nuevos 
;   sensores (ej. temperatura, humedad, etc.).
; ==========================================================

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Velocidad base del Monitor Serial
monitor_speed = 115200

; Banderas de comunicación nativa USB para Mac
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; Aquí irán las librerías exclusivas de este nodo
lib_deps =
    ; [FUTURO] Añadir librerías aquí cuando se defina el hardware