; ==========================================================
; Proyecto: BIO-ALERT (AXIS.ops)
; Nodo: BIO-ACOUSTIC-HEALTH
; Hardware: ESP32-S3 DevKitC-1
; ==========================================================

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; ==========================================================
; PUERTOS Y MONITOR SERIAL (Optimizado para Mac)
; ==========================================================
; El asterisco (*) hace que PlatformIO encuentre automáticamente 
; el puerto del ESP32 sin preguntarte cada vez que subes código.
upload_port = /dev/cu.usb*
monitor_port = /dev/cu.usb*
monitor_speed = 115200

; ==========================================================
; BANDERAS DE COMPILACIÓN (VITAL PARA ESP32-S3 EN MAC)
; ==========================================================
; Fuerza al chip a enrutar la consola Serial por el cable USB nativo,
; evitando que el puerto desaparezca o se bloquee.
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

; ==========================================================
; LIBRERÍAS EXTERNAS
; ==========================================================
; I2S, SPI y SD son nativas. Futuras librerías van aquí.
lib_deps =